"""empty message

Revision ID: 70164989ada1
Revises: 
Create Date: 2021-10-06 12:04:19.301673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70164989ada1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('LawyerID', sa.Integer(), nullable=False))
    op.drop_index('ix_bills_Lawyer ID', table_name='bills')
    op.create_index(op.f('ix_bills_LawyerID'), 'bills', ['LawyerID'], unique=False)
    op.drop_constraint('bills_Lawyer ID_fkey', 'bills', type_='foreignkey')
    op.create_foreign_key(None, 'bills', 'lawyers', ['LawyerID'], ['id'])
    op.drop_column('bills', 'Lawyer ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('Lawyer ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.create_foreign_key('bills_Lawyer ID_fkey', 'bills', 'lawyers', ['Lawyer ID'], ['id'])
    op.drop_index(op.f('ix_bills_LawyerID'), table_name='bills')
    op.create_index('ix_bills_Lawyer ID', 'bills', ['Lawyer ID'], unique=False)
    op.drop_column('bills', 'LawyerID')
    # ### end Alembic commands ###
