"""redis

Revision ID: cdff3f403de2
Revises: 
Create Date: 2021-09-13 14:12:17.205549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdff3f403de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'Token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('Token', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
